# Agent parameters for note interpreter
max_clarification_rounds:
  value: 2
  description: Maximum number of clarification rounds before finalizing output.
temperature:
  value: 0.0
  description: LLM temperature for deterministic output in tests. 